INSERT INTO Types (Type, Kind)
VALUES ('MODIFIER_UNIT_ADJUST_VALID_TERRAIN', 'KIND_MODIFIER'),
        ('ABILITY_CANT_ENTER_COAST', 'KIND_ABILITY');

INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType)
SELECT 'MODIFIER_UNIT_ADJUST_VALID_TERRAIN', 'COLLECTION_OWNER', 'EFFECT_ADJUST_UNIT_VALID_TERRAIN';

INSERT INTO Modifiers (ModifierId, ModifierType)
VALUES ('MODIFIER_PREVENT_UNIT_ENTER_COAST', 'MODIFIER_UNIT_ADJUST_VALID_TERRAIN');
 
INSERT INTO ModifierArguments (ModifierId, Name, Type, Value)
VALUES ('MODIFIER_PREVENT_UNIT_ENTER_COAST', 'TerrainType', 'ARGTYPE_IDENTITY', 'TERRAIN_COAST'),
        ('MODIFIER_PREVENT_UNIT_ENTER_COAST', 'Valid', 'ARGTYPE_IDENTITY', 0);

INSERT INTO Tags (Tag, Vocabulary)
SELECT 'CLASS_NO_COAST_ENTRY', 'ABILITY_CLASS';

INSERT INTO TypeTags (Type, Tag)
SELECT 'ABILITY_CANT_ENTER_COAST', 'CLASS_NO_COAST_ENTRY';

INSERT INTO UnitAbilities (UnitAbilityType, Name, Description)
SELECT 'ABILITY_CANT_ENTER_COAST', 'LOC_ABILITY_CANT_ENTER_COAST', 'LOC_ABILITY_CANT_ENTER_COAST_DESC';

INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId)
VALUES ('ABILITY_CANT_ENTER_COAST', 'MODIFIER_PREVENT_UNIT_ENTER_COAST');

INSERT INTO TypeTags (Type, Tag)
VALUES ('UNIT_ANIMAL_NILE_CROCODILE', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_FRESHWATER_CROCODILE', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_CHEETAH', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_BLACKCAIMAN', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_AMERICANCROCODILE', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_TASMANIANWOLF', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_DINGO', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_JACKAL', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_SPECTACLEDBEAR', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_BLACKBEAR', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_MANEDWOLF', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_HYENA', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_RHINOCEROS', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_HIPPO', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_GORILLA', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_PANDA', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_POLARBEAR', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_GRIZZLYBEAR', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_PUMA', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_WOLF', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_BIGCATS_WHITE_TIGER', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_BIGCATS_TIGER', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_BIGCATS_PANTHER', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_BIGCATS_JAGUAR', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_BIGCATS_LION', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_BIGCATS_SNOW_LEOPARD', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_BIGCATS_LEOPARD', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_MANTA', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_ORCA', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_TIGERSHARK', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_BULLSHARK', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_HAMMERHEAD', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_WHITESHARK', 'CLASS_NO_COAST_ENTRY'),
        ('UNIT_ANIMAL_KRAKEN', 'CLASS_NO_COAST_ENTRY'),		
        ('UNIT_ANIMAL_HUMPBACK_WHALE', 'CLASS_NO_COAST_ENTRY');